### ISSUE TITLE
visvis example without picture and font

### ISSUE THREAD

**Issue by GoogleCodeExporter** [almarklein/visvis#80]
```
Hello everyone!

I am trying to properly install visvis on my 7.3 debian x86.
Firstly I have installed all GPU drivers, all dependenciess etc.
I don't know what can i do more.
When i am trying execute example program, there are errors, labels are not 
displayed and jpg picture is not loaded.

Thank you:)

terminal output:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/visvis/backends/qtcommon.py", line 216, in paintEvent
    self.figure.OnDraw()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseFigure.py", line 773, in OnDraw
    self._Draw(mode)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseFigure.py", line 860, in _Draw
    child._DrawTree(mode, pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 123, in _DrawTree
    base.Wibject._DrawTree(self, mode, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 191, in _DrawTree
    item._DrawTree(mode,pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 184, in _DrawTree
    self.OnDraw()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 817, in OnDraw
    self._OnDrawInMode(DRAW_NORMAL, self.bgcolor)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 877, in _OnDrawInMode
    self._OnDrawContent(mode, bgcolor, pos, pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 1005, in _OnDrawContent
    item._DrawTree(mode, pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 184, in _DrawTree
    self.OnDraw()
  File "/usr/local/lib/python2.7/dist-packages/visvis/wobjects/textures.py", line 535, in OnDraw
    self._texture1.Enable(-1)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseTexture.py", line 216, in Enable
    self._SetDataNow()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseTexture.py", line 353, in _SetDataNow
    self._texId = gl.glGenTextures(1)
  File "latebind.pyx", line 44, in OpenGL_accelerate.latebind.Curry.__call__ (src/latebind.c:1123)
  File "/usr/local/lib/python2.7/dist-packages/OpenGL/GL/exceptional.py", line 189, in glGenTextures
    baseFunction( count, textures)
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:931)
  File "wrapper.pyx", line 296, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:5803)
  File "wrapper.pyx", line 158, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call (src/wrapper.c:3930)
  File "wrapper.pyx", line 125, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3384)
  File "wrapper.pyx", line 113, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3212)
  File "wrapper.pyx", line 209, in OpenGL_accelerate.wrapper.CallFuncPyConverter.c_call (src/wrapper.c:4730)
  File "arraydatatype.pyx", line 171, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray (src/arraydatatype.c:3845)
  File "arraydatatype.pyx", line 58, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup (src/arraydatatype.c:2106)
TypeError: ("No array-type handler for type <class 'ctypes.c_ulong'> (value: 
c_ulong(0L)) registered", None)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/visvis/backends/qtcommon.py", line 216, in paintEvent
    self.figure.OnDraw()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseFigure.py", line 773, in OnDraw
    self._Draw(mode)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseFigure.py", line 860, in _Draw
    child._DrawTree(mode, pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 123, in _DrawTree
    base.Wibject._DrawTree(self, mode, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 191, in _DrawTree
    item._DrawTree(mode,pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 184, in _DrawTree
    self.OnDraw()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 817, in OnDraw
    self._OnDrawInMode(DRAW_NORMAL, self.bgcolor)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 877, in _OnDrawInMode
    self._OnDrawContent(mode, bgcolor, pos, pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 1005, in _OnDrawContent
    item._DrawTree(mode, pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 184, in _DrawTree
    self.OnDraw()
  File "/usr/local/lib/python2.7/dist-packages/visvis/wobjects/textures.py", line 535, in OnDraw
    self._texture1.Enable(-1)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseTexture.py", line 216, in Enable
    self._SetDataNow()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseTexture.py", line 353, in _SetDataNow
    self._texId = gl.glGenTextures(1)
  File "latebind.pyx", line 44, in OpenGL_accelerate.latebind.Curry.__call__ (src/latebind.c:1123)
  File "/usr/local/lib/python2.7/dist-packages/OpenGL/GL/exceptional.py", line 189, in glGenTextures
    baseFunction( count, textures)
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:931)
  File "wrapper.pyx", line 296, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:5803)
  File "wrapper.pyx", line 158, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call (src/wrapper.c:3930)
  File "wrapper.pyx", line 125, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3384)
  File "wrapper.pyx", line 113, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3212)
  File "wrapper.pyx", line 209, in OpenGL_accelerate.wrapper.CallFuncPyConverter.c_call (src/wrapper.c:4730)
  File "arraydatatype.pyx", line 171, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray (src/arraydatatype.c:3845)
  File "arraydatatype.pyx", line 58, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup (src/arraydatatype.c:2106)
TypeError: ("No array-type handler for type <class 'ctypes.c_ulong'> (value: 
c_ulong(0L)) registered", None)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/visvis/backends/qtcommon.py", line 216, in paintEvent
    self.figure.OnDraw()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseFigure.py", line 773, in OnDraw
    self._Draw(mode)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseFigure.py", line 860, in _Draw
    child._DrawTree(mode, pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 123, in _DrawTree
    base.Wibject._DrawTree(self, mode, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 191, in _DrawTree
    item._DrawTree(mode,pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 184, in _DrawTree
    self.OnDraw()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 817, in OnDraw
    self._OnDrawInMode(DRAW_NORMAL, self.bgcolor)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 930, in _OnDrawInMode
    item._DrawTree(DRAW_SCREEN)      
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 191, in _DrawTree
    item._DrawTree(mode,pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 180, in _DrawTree
    self.OnDrawScreen()            
  File "/usr/local/lib/python2.7/dist-packages/visvis/text/text_base.py", line 586, in OnDrawScreen
    self._screenx, self._screeny, depthToZ(self._screenz) )
  File "/usr/local/lib/python2.7/dist-packages/visvis/text/text_freetype.py", line 586, in Draw
    simpleTextureDraw(vertices, texCords, self.atlas, textObject.textColor)
  File "/usr/local/lib/python2.7/dist-packages/visvis/text/text_base.py", line 247, in simpleTextureDraw
    texture.Enable()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseTexture.py", line 216, in Enable
    self._SetDataNow()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseTexture.py", line 353, in _SetDataNow
    self._texId = gl.glGenTextures(1)
  File "latebind.pyx", line 44, in OpenGL_accelerate.latebind.Curry.__call__ (src/latebind.c:1123)
  File "/usr/local/lib/python2.7/dist-packages/OpenGL/GL/exceptional.py", line 189, in glGenTextures
    baseFunction( count, textures)
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:931)
  File "wrapper.pyx", line 296, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:5803)
  File "wrapper.pyx", line 158, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call (src/wrapper.c:3930)
  File "wrapper.pyx", line 125, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3384)
  File "wrapper.pyx", line 113, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3212)
  File "wrapper.pyx", line 209, in OpenGL_accelerate.wrapper.CallFuncPyConverter.c_call (src/wrapper.c:4730)
  File "arraydatatype.pyx", line 171, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray (src/arraydatatype.c:3845)
  File "arraydatatype.pyx", line 58, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup (src/arraydatatype.c:2106)
TypeError: ("No array-type handler for type <class 'ctypes.c_ulong'> (value: 
c_ulong(0L)) registered", None)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/visvis/backends/qtcommon.py", line 216, in paintEvent
    self.figure.OnDraw()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseFigure.py", line 773, in OnDraw
    self._Draw(mode)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseFigure.py", line 860, in _Draw
    child._DrawTree(mode, pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 123, in _DrawTree
    base.Wibject._DrawTree(self, mode, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 191, in _DrawTree
    item._DrawTree(mode,pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 184, in _DrawTree
    self.OnDraw()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 817, in OnDraw
    self._OnDrawInMode(DRAW_NORMAL, self.bgcolor)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 930, in _OnDrawInMode
    item._DrawTree(DRAW_SCREEN)      
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 191, in _DrawTree
    item._DrawTree(mode,pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 180, in _DrawTree
    self.OnDrawScreen()            
  File "/usr/local/lib/python2.7/dist-packages/visvis/text/text_base.py", line 586, in OnDrawScreen
    self._screenx, self._screeny, depthToZ(self._screenz) )
  File "/usr/local/lib/python2.7/dist-packages/visvis/text/text_freetype.py", line 586, in Draw
    simpleTextureDraw(vertices, texCords, self.atlas, textObject.textColor)
  File "/usr/local/lib/python2.7/dist-packages/visvis/text/text_base.py", line 247, in simpleTextureDraw
    texture.Enable()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseTexture.py", line 216, in Enable
    self._SetDataNow()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseTexture.py", line 353, in _SetDataNow
    self._texId = gl.glGenTextures(1)
  File "latebind.pyx", line 44, in OpenGL_accelerate.latebind.Curry.__call__ (src/latebind.c:1123)
  File "/usr/local/lib/python2.7/dist-packages/OpenGL/GL/exceptional.py", line 189, in glGenTextures
    baseFunction( count, textures)
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:931)
  File "wrapper.pyx", line 296, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:5803)
  File "wrapper.pyx", line 158, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call (src/wrapper.c:3930)
  File "wrapper.pyx", line 125, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3384)
  File "wrapper.pyx", line 113, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3212)
  File "wrapper.pyx", line 209, in OpenGL_accelerate.wrapper.CallFuncPyConverter.c_call (src/wrapper.c:4730)
  File "arraydatatype.pyx", line 171, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray (src/arraydatatype.c:3845)
  File "arraydatatype.pyx", line 58, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup (src/arraydatatype.c:2106)
TypeError: ("No array-type handler for type <class 'ctypes.c_ulong'> (value: 
c_ulong(0L)) registered", None)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/visvis/backends/qtcommon.py", line 216, in paintEvent
    self.figure.OnDraw()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseFigure.py", line 773, in OnDraw
    self._Draw(mode)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseFigure.py", line 860, in _Draw
    child._DrawTree(mode, pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 123, in _DrawTree
    base.Wibject._DrawTree(self, mode, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 191, in _DrawTree
    item._DrawTree(mode,pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 184, in _DrawTree
    self.OnDraw()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 817, in OnDraw
    self._OnDrawInMode(DRAW_NORMAL, self.bgcolor)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 877, in _OnDrawInMode
    self._OnDrawContent(mode, bgcolor, pos, pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/axes.py", line 1005, in _OnDrawContent
    item._DrawTree(mode, pickerHelper)
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/base.py", line 184, in _DrawTree
    self.OnDraw()
  File "/usr/local/lib/python2.7/dist-packages/visvis/wobjects/textures.py", line 739, in OnDraw
    self._texture1.Enable(-1) # -1 means do not bind right now
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseTexture.py", line 216, in Enable
    self._SetDataNow()
  File "/usr/local/lib/python2.7/dist-packages/visvis/core/baseTexture.py", line 353, in _SetDataNow
    self._texId = gl.glGenTextures(1)
  File "latebind.pyx", line 44, in OpenGL_accelerate.latebind.Curry.__call__ (src/latebind.c:1123)
  File "/usr/local/lib/python2.7/dist-packages/OpenGL/GL/exceptional.py", line 189, in glGenTextures
    baseFunction( count, textures)
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:931)
  File "wrapper.pyx", line 296, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:5803)
  File "wrapper.pyx", line 158, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call (src/wrapper.c:3930)
  File "wrapper.pyx", line 125, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3384)
  File "wrapper.pyx", line 113, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3212)
  File "wrapper.pyx", line 209, in OpenGL_accelerate.wrapper.CallFuncPyConverter.c_call (src/wrapper.c:4730)
  File "arraydatatype.pyx", line 171, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray (src/arraydatatype.c:3845)
  File "arraydatatype.pyx", line 58, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup (src/arraydatatype.c:2106)
TypeError: ("No array-type handler for type <class 'ctypes.c_ulong'> (value: 
c_ulong(0L)) registered", None)




```

Original issue reported on code.google.com by `przemekk...@gmail.com` on 29 Jan 2014 at 10:41

**Comment by almarklein** [comment]
Looks like an issue with PyOpenGL.
