### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by torquil** [almarklein/visvis#87]
When importing visvis, I'm getting this error:

`$ python3
Python 3.5.1+ (default, Feb 24 2016, 11:28:57) 
[GCC 5.3.1 20160220] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import visvis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tmac/.local/lib/python3.5/site-packages/visvis/__init__.py", line 59, in <module>
    from visvis.wobjects import *
  File "/home/tmac/.local/lib/python3.5/site-packages/visvis/wobjects/__init__.py", line 20, in <module>
    from visvis.wobjects.polygonalModeling import Mesh, OrientableMesh
  File "/home/tmac/.local/lib/python3.5/site-packages/visvis/wobjects/polygonalModeling.py", line 406, in <module>
    import visvis.processing as processing
  File "/home/tmac/.local/lib/python3.5/site-packages/visvis/processing/__init__.py", line 82, in <module>
    _functionNames = _insertFunctions()
  File "/home/tmac/.local/lib/python3.5/site-packages/visvis/processing/__init__.py", line 69, in _insertFunctions
    mod = __import__("visvis.processing."+funname, fromlist=[funname])
  File "/home/tmac/.local/lib/python3.5/site-packages/visvis/processing/calculateNormals.py", line 14, in <module>
    faces = np.arange(N); faces.shape = len(v)/3,3
TypeError: 'float' object cannot be interpreted as an integer
>>>`

I'm using Visvis 1.9.2, PyOpenGL 3.1.0 and Numpy 1.11.0b3.

Best regards,
Torquil Sørensen

**Comment by almarklein** [comment]
Thanks for the report. I could not reproduce your error (maybe because my numpy is 1.10.4), but I could see why it occurred. Should be fixed, let me know if you run into anything else.
